name: pkg_mysql
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  
  mysql_client: ^0.0.27  
  pkg_utils:
    git:
      url: https://github.com/Toph92/pkg_utils
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
